keys:
  - &admin_misty age1ztwty6h4qefyzdqkqy6sre4lqan3zxa8mk90dzrc8lkm8f5439ts3dksmq
  - &server_mistyttmdev age1vmeythszeduft4ma5h3hfvtp30rz2v70tja8amfchs50rhuwf9jsljkf5d
  - &server_kennel age19ysep57z02y3hhf6c75cvz7njd66p2cqt85g4xqxzmgvk5slmsxq04jyp7
  - &laptop age19ltwngxype68geu76vvssxsyvpdavrcnv44zhs2vrxt32lc42urqllwtku
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_misty
      - *server_mistyttmdev
      - *server_kennel
      - *laptop
