keys:
  - &admin_misty age1ztwty6h4qefyzdqkqy6sre4lqan3zxa8mk90dzrc8lkm8f5439ts3dksmq
  - &server_mistyttmdev age15qjgy98838e727ajh8v8h0enn340lzxyx4r0vas73e2ujjxkvsmqvtyw9u
  - &server_kennel age19ysep57z02y3hhf6c75cvz7njd66p2cqt85g4xqxzmgvk5slmsxq04jyp7
  - &laptop age1rtqyx0569wsyyq2885f5c5ywnkfj36dwcz5usxep7zx8tkfcussqey3ndc
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_misty
      - *server_mistyttmdev
      - *server_kennel
      - *laptop
