keys:
  - &admin_misty age1ztwty6h4qefyzdqkqy6sre4lqan3zxa8mk90dzrc8lkm8f5439ts3dksmq
  - &server_mistyttmdev age1vmeythszeduft4ma5h3hfvtp30rz2v70tja8amfchs50rhuwf9jsljkf5d
  - &server_kennel age1p0xdp58feqwswzq8wq0wfqmahez5s5maccz3fkzu5hfjqm65259s7sy2mh
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_misty
      - *server_mistyttmdev
      - *server_kennel
