name: Build and Cache NixOS Systems
on:
  workflow_run:
    workflows: ["Update Flake Inputs"]
    types: [completed]
    branches: [main]
  pull_request:
    paths:
      - flake.lock
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Hydra jobset
    runs-on: ubuntu-latest
    if: >-
      ${{
        github.event_name != 'workflow_run' ||
        github.event.workflow_run.conclusion == 'success'
      }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Maximize disk space
        uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: rampage

      - name: Install Lix
        uses: samueldr/lix-gha-installer-action@latest
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
            max-jobs = auto
            cores = 0
            substitute = true
            builders =

      - name: Enable Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: opinionatedcache
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: true

      - name: Install nix-fast-build
        run: |
          nix profile install github:Mic92/nix-fast-build

      - name: Build Hydra jobs
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
        run: |
          nix-fast-build \
            --flake .#hydraJobs \
            --skip-cached \
            --cachix-cache opinionatedcache \
            --skip-cached \
            --stream-json-lines \
            --option allow-import-from-derivation false \
