matrix-alertmanager-token: ENC[AES256_GCM,data:JwsurHKhP8n92NQDOBRnDiz+WN/sah8V6M86nv/dTF3UoG/UWAqzVw==,iv:tj2iCagMN+/pmoQ0wl4EPrtq4TxAptc46rlK4r4A92E=,tag:wquWfUjkPpWy59KCkJ34AA==,type:str]
matrix-alertmanager-secret: ENC[AES256_GCM,data:N0dirM0oTAEdBC/IZfaNaW8+6sGNkulv698VgqvyvnBQal4DPQ0B8NBuMj8cljbq/50e5Pvafp1FS+gBXcbe76aUBhC6Du0v4jyQDaXhnXJvx4cB8Qv3C44eaenJmAFdKGpfqkkP9Te2oB+Vy2n/QYXTLWOJUPMkBnNAHo5MqlU=,iv:a2g0iZo6GYgbcTCqmCPZ2OXodsRtDGao/Bow1VP1NmQ=,tag:wDY5+n7bUDfGgbOEOJnZGQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDN2hXaEVNdENWNlVSOWFU
            SFkwRFRUQVRIWGp5ank2MjR1amJ2MDczbjM0CjVFWDdtMDRZWDJMWnB5SXJhYXFN
            c0wrOTJ0TmNKdEJCakErNVZQSkY1OE0KLS0tIFRTdjlVUHQzOVJXbWVBMkhldzhN
            OTJlVUN4c0R5ZllVQ0ZJNmQvM2taUWMKR1cQG0uxSuI8BqjxwkGEX4fosvwSYzvb
            Bp9WZiFLg0zN/3E8pCcAAbB0bbIyk1hykWINOPHZdCelZE6EAMhXuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ztwty6h4qefyzdqkqy6sre4lqan3zxa8mk90dzrc8lkm8f5439ts3dksmq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByc21uNnJ1VWxoQ2lWd0pz
            d0Q1UnFVdms0Nkp4WkNwd0M0aW0zQmZrOEZJCjJpNWpzQzFXNlphUXZ2V3hDZmND
            TGZFVzhsS2tsbTRJTmgwd0I5b2JLR2sKLS0tIFpaMGhQNkxzUkxEOHlEaFZVdEdk
            ZElvVk9WVHNHdHRKMGMrSlkrQndnVDAKGkJn4YGbD+0OSdd5ymEcSHun68bmf0x0
            z6SUsO0PuprNvJgKUv8MV1Y42Az3Q3wH002f+cdgxdCeMf1xbX5XMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15qjgy98838e727ajh8v8h0enn340lzxyx4r0vas73e2ujjxkvsmqvtyw9u
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSY1c3N0xXYnNOdnhYOXk5
            UmhxU3NNb3huNjQ4bEo4YmxkOTJaaFdsZmc4CmZiYmtWZjVNd1U4L2ljUTJ0cVhW
            ZnRSNXMyNE1qSXpMTVVMQjkyLzVGQU0KLS0tIDkxUk9WMWV5azg3dTQzWTkza3pH
            SFIrY0FkUGRjSFFxWExzbU1DL3hFUmMKS41l6RwCPHGdjWO3uBa4YIGkiJElaGo1
            1pb8fyf4X65ig6Td7xjYiWIkOtxVhs9uTXx1Kh8IMfW/HijxkFn6hg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19ysep57z02y3hhf6c75cvz7njd66p2cqt85g4xqxzmgvk5slmsxq04jyp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeFJLaHNocXFWdnZkQy83
            UEl0VStiSnNUOU5LT3pseUh5aEZmbnNDWlZZCkRjTWwzSS95dlNYMkcwSHoxWGZP
            OTJydzBSZmo3NUxUd0FtNHI3WXhHSUEKLS0tIDVJTmVFSy9uMHZOTzRuT0hLb0lW
            VkMvVGdaMkd6aDBaVTM4OEpmVXM0NEkKo5RxNnhybq+RCYWVASnAlgIptLT3olqf
            940ebSm+KWMWdVpN9OKwtOa+voMYg25RdXPAoedLBlHom5tMRtp5rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rtqyx0569wsyyq2885f5c5ywnkfj36dwcz5usxep7zx8tkfcussqey3ndc
    lastmodified: "2026-08-26T11:44:37Z"
    mac: ENC[AES256_GCM,data:ktTrfCb+y65xu5rUix56g2bIPpnv2HZzLR3UBIz3X2ixNvhAYrqFgi82i5x/W+vGPN+ADSF/olPnosjWyEw/aFmnbJNVsKg53BCGeGcugsybLpFTWNSynzma533ckGht8IHbqhzLj7ZocCKNqSzI+jSK4WAL0n2SuIKeGlG/b5Y=,iv:I0LWV+iCqwCFEkNhhfcVg5Psgxs1b8f073FUdPexaoM=,tag:FMamA3y4S1BgUjrtofennw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
